---
title: "Appendix"
author: "Adina Zhang"
date: "April 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Tuning parameters

# Tuning lambda for lasso through cross validation
set.seed(123)
cv_lasso = cv.glmnet(x, y, alpha = 1)
best_lambda = cv_lasso$lambda.min
plot_glmnet(cv_lasso$glmnet.fit)

# Tuning for MARS
# Create a tuning grid
hyper_grid = expand.grid(
  degree = 1:3, 
  nprune = seq(2, 70, length.out = 20) %>% floor()
  )

set.seed(1)
# Cross validated model
tuned_mars = train(
  x = subset(life_analysis, select = -life_expectancy),
  y = life_analysis$life_expectancy,
  method = "earth",
  metric = "RMSE",
  trControl = trainControl(method = "cv", number = 10),
  tuneGrid = hyper_grid
)

# best model
tuned_mars$bestTune

ggplot(tuned_mars)

```

```{r}
# Function to indicate y outcomes
y_data = function(data){
  y = data$life_expectancy
}

# Function to calculate Lasso RMSE from test dataset
lasso_rmse = function(model, x2, y2){
  predictions = model %>% predict(x2) %>% as.vector()
  rmse_lasso = RMSE(predictions, y2)
  return(rmse_lasso)
}

set.seed(281)
# Set up 10-fold cross validation
# Create training and test datasets
cv_df = crossv_kfold(life_analysis, k = 10) %>% 
  mutate(train = map(train, as_tibble),
         test = map(test, as_tibble),
         x = map(train, ~model.matrix(life_expectancy ~ ., data = .x)[,-3]),
         x2 = map(test, ~model.matrix(life_expectancy ~ ., data = .x)[,-3]),
         y = map(train, y_data),
         y2 = map(test, y_data))

# Fit four models: Least squares, lasso, GAM, MARS 
# Tuning parameters already selected
# Calculate RMSE from each model
cv_df = cv_df %>% 
  mutate(ls_mod = map(train, ~lm(life_expectancy ~ ., data = .x)), 
         lasso_mod = map2(x, y, ~glmnet(x = .x, 
                                        y = .y, alpha = 1, 
                                        lambda = best_lambda)),
         gam = map(train, ~ gam(life_expectancy ~ s(gdp) + 
                                  s(hiv_aids) + 
                                  s(alcohol) + 
                                  s(bmi) + 
                                  s(hepatitis_b) + 
                                  s(total_expenditure) + 
                                  s(thinness_1_19_years) + 
                                  s(under_five_deaths) + 
                                  year + 
                                  status + 
                                  adult_mortality + 
                                  income_composition_of_resources + 
                                  schooling + 
                                  s(diphtheria), 
                                data = .x)),
         mars = map(train, ~ earth(life_expectancy ~ . , data = life_analysis, 
                                   degree = 2, nprune = 27), data = .x)) %>% 
  mutate(rmse_ls = map2_dbl(ls_mod, test, ~rmse(model = .x, data = .y)),
         rmse_lasso = pmap_dbl(list(lasso_mod, x2, y2), lasso_rmse),
         rmse_gam = map2_dbl(gam, test, ~ rmse(model = .x, data = .y)),
         rmse_mars = map2_dbl(mars, test, ~ rmse(model = .x, data = .y)))

# Boxplot of RMSE from all four model fits
cv_df %>% 
  select(starts_with("rmse")) %>% 
  gather(key = model, value = rmse) %>% 
  mutate(model = str_replace(model, "rmse_", ""),
         model = fct_inorder(model)) %>% 
  ggplot(aes(y = rmse, fill = model)) + 
  geom_boxplot() + 
  labs(
    title = "10-Fold Cross Validation Results"
  ) +
  theme_bw()
```

