---
title: "LS, Lasso, Ridge Regression"
author: "Adina Zhang"
date: "April 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(caret)
library(glmnet)
library(modelr)
```

```{r, message = FALSE}
# Load dataset
life_analysis = read_csv("./Life Expectancy Data.csv") %>% 
  janitor::clean_names() %>%
  select(-country, -population, -infant_deaths, -measles, 
         -polio, -thinness_5_9_years, -percentage_expenditure) %>% 
  mutate(status = factor(status),
         status = fct_recode(status, "0" = "Developing", "1" = "Developed"),
         status = ifelse(status == "1", 1, 0)) 

life_analysis = na.omit(life_analysis)

# Split data into test and training datasets
set.seed(1)
train_rows = createDataPartition(life_analysis$life_expectancy,
                                 p = 0.75,
                                 list = F)

# Specify test and training datasets
train_df = life_analysis[train_rows,]
# Test Set
test_df = life_analysis[-train_rows,]

# Predictor variable
x = model.matrix(life_expectancy~., train_df)[,-3]
x2 = model.matrix(life_expectancy~., test_df)[,-3]
# Outcome variable
y = train_df$life_expectancy
y2 = test_df$life_expectancy
```


## Least Squares Model

```{r}
# Set up cross validation measures
ctrl1 = trainControl(method = "cv", number = 10)

set.seed(2)
# Least squares model
ls.fit = train(life_expectancy ~.,
               data = train_df,
               method = 'lm',
               trControl = ctrl1)
# MSE Calculation
predy.lm = predict(ls.fit$finalModel, newdata = test_df)
mse = mean((predy.lm - test_df$life_expectancy)^2)
```

## Ridge Regression

```{r}
set.seed(123)
# Ridge model
ridge.fit = train(x, y,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha = 0,
                                         lambda = exp(seq(-2, 20, length = 100))),
                  trControl = ctrl1)
best.lambda = ridge.fit$bestTune$lambda

# MSE Calculation
predy.ridge = predict(ridge.fit$finalModel, 
                      newx = x2,
                      s = best.lambda, type = "response")
mse_ridge = mean((predy.ridge - y2)^2)

plot(ridge.fit, xTrans = function(x) log(x))

ridge_coefficients = predict(ridge.fit$finalModel, newx = x2,
                       s = best.lambda, type = "coefficients")
summary(ridge_coefficients)
```

### Lasso

```{r}
set.seed(123)
# Ridge model
lasso.fit = train(x, y,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha = 1,
                                         lambda = exp(seq(-2, 5, length = 100))),
                  trControl = ctrl1)
best.lambda = lasso.fit$bestTune$lambda

set.seed(123)
cv_lasso = cv.glmnet(x, y, alpha = 1)
best_lambda = cv_lasso$lambda.min

# MSE Calculation
predy.lasso = predict(lasso.fit$finalModel, 
                      newx = x2,
                      s = best.lambda, type = "response")
mse_lasso = mean((predy.lasso - y2)^2)

plot(lasso.fit, xTrans = function(x) log(x))

# Summary of coefficients
lasso_coefficients = predict(lasso.fit$finalModel, newx = x2,
                       s = best.lambda, type = "coefficients")
summary(lasso_coefficients)
```


```{r}

y_data = function(data){
  y = data$life_expectancy
}

lasso_rmse = function(model, x2, y2){
  predictions = model %>% predict(x2) %>% as.vector()
  rmse_lasso = RMSE(predictions, y2)
  return(rmse_lasso)
}

set.seed(281)
cv_df = crossv_kfold(life_analysis, k = 10) %>% 
  mutate(train = map(train, as_tibble),
         test = map(test, as_tibble),
         x = map(train, ~model.matrix(life_expectancy ~ ., data = .x)[,-3]),
         x2 = map(test, ~model.matrix(life_expectancy ~ ., data = .x)[,-3]),
         y = map(train, y_data),
         y2 = map(test, y_data))

# Fit Models
cv_df = cv_df %>% 
  mutate(ls_mod = map(train, ~lm(life_expectancy ~ ., data = .x)), 
         lasso_mod = map2(x, y, ~glmnet(x = .x, 
                                        y = .y, alpha = 1, 
                                        lambda = best_lambda)),
         gam = map(train, ~ gam(life_expectancy ~ s(gdp) + 
                                  s(hiv_aids) + 
                                  s(alcohol) + 
                                  s(bmi) + 
                                  s(hepatitis_b) + 
                                  s(total_expenditure) + 
                                  s(thinness_1_19_years) + 
                                  s(under_five_deaths) + 
                                  year + 
                                  status + 
                                  adult_mortality + 
                                  income_composition_of_resources + 
                                  schooling + 
                                  s(diphtheria), 
                                data = .x)),
         mars = map(train, ~ earth(life_expectancy ~ . , data = life_analysis, 
                                   degree = 2, nprune = 27), data = .x)) %>% 
  mutate(rmse_ls = map2_dbl(ls_mod, test, ~rmse(model = .x, data = .y)),
         rmse_lasso = pmap_dbl(list(lasso_mod, x2, y2), lasso_rmse),
         rmse_gam = map2_dbl(gam, test, ~ rmse(model = .x, data = .y)),
         rmse_mars = map2_dbl(mars, test, ~ rmse(model = .x, data = .y)))

cv_df %>% 
  select(starts_with("rmse")) %>% 
  gather(key = model, value = rmse) %>% 
  mutate(model = str_replace(model, "rmse_", ""),
         model = fct_inorder(model)) %>% 
  ggplot(aes(y = rmse, fill = model)) + 
  geom_boxplot() + 
  labs(
    title = "10-Fold Cross Validation Results"
  ) +
  theme_bw()
```

